# Generated by Django 2.0.5 on 2018-05-26 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=150)),
                ('fileType', models.CharField(choices=[('.pdf', 'Portable Document Format (PDF)'), ('.txt', 'Documento de Texto'), ('.doc', 'Documento do Word'), ('.jpg', 'Imagem JPG'), ('.png', 'Portable Network Graphics (PNG)'), ('.mp3', 'Arquivo de Áudio MP3')], default='txt', help_text='File Format', max_length=5)),
                ('language', models.CharField(max_length=50)),
                ('coverage', models.CharField(max_length=50)),
                ('rights', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Document Date')),
                ('fileFormat', models.CharField(max_length=50)),
                ('submissionDate', models.DateField(verbose_name='Submission Date')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('doc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cedoc.Doc')),
                ('Image', models.ImageField(upload_to='images/')),
            ],
            bases=('cedoc.doc',),
        ),
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('doc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cedoc.Doc')),
                ('File', models.FileField(upload_to='texts/')),
            ],
            bases=('cedoc.doc',),
        ),
        migrations.AddField(
            model_name='contributor',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedoc.Doc'),
        ),
    ]
