# Generated by Django 2.0.5 on 2018-06-12 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', help_text='Name of the Document', max_length=300, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('publisher', models.CharField(default='FAC-UnB', max_length=150, verbose_name='Publisher')),
                ('fileType', models.CharField(choices=[('book', 'Printed Book'), ('.pdf', 'Portable Document Format (PDF)'), ('.mp3', 'MP3 Audio'), ('.wav', 'Microsoft Wave (WAV)'), ('.aif', 'Audio Interchange File Format (AIFF)'), ('.mp4', 'MP4 Format'), ('.mpeg', 'MPEG Format')], default='.txt', max_length=5, verbose_name='File Format')),
                ('coverage', models.CharField(choices=[('L', 'Local'), ('R', 'Regional'), ('I', 'International'), ('N', 'National')], default='R', max_length=2, verbose_name='Coverage')),
                ('rights', models.CharField(default='Free Access', help_text='Access Rights', max_length=100, verbose_name='Rights')),
                ('source', models.CharField(default='Faculdade de Comunicação - FAC', max_length=100, verbose_name='Source')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Document Date')),
                ('fileFormat', models.CharField(choices=[('AN', 'Analog'), ('DG', 'Digital')], default='DG', max_length=2, verbose_name='Media Format')),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(choices=[(True, 'Sim'), (False, 'Nao')], default=False, verbose_name='Accept file')),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('doc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cedoc.Doc')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Audio Duration')),
                ('language', models.CharField(blank=True, default='None', max_length=50, verbose_name='Language')),
                ('File', models.FileField(blank=True, upload_to='audio/')),
            ],
            bases=('cedoc.doc',),
        ),
        migrations.CreateModel(
            name='CampusJournal',
            fields=[
                ('doc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cedoc.Doc')),
                ('author', models.CharField(default='Jornalismo', max_length=50, verbose_name='Author')),
                ('produtor', models.CharField(default='Faculdade de Comunicação da Universidade de Brasília', max_length=100, verbose_name='Producer')),
                ('editor', models.CharField(default='Faculdade de Comunicação da Universidade de Brasília', max_length=100, verbose_name='Editor')),
                ('collaborator', models.CharField(default='CEDOC', max_length=100, verbose_name='Collaborator')),
                ('language', models.CharField(default='Português', max_length=50, verbose_name='Language')),
                ('license', models.CharField(default='CC BY-NC-ND 4.0', max_length=50, verbose_name='License')),
                ('repoLocation', models.CharField(default='Coleções Especiais - BCE', max_length=100, verbose_name='Location in Collection')),
                ('cedocLocation', models.CharField(default='Arquivo Físico', max_length=100, verbose_name='Location in CEDOC')),
                ('size', models.CharField(default='26.00 x 40.00 cm', help_text='In centimeters', max_length=100, verbose_name='Physical Dimensions')),
                ('File', models.FileField(blank=True, upload_to='texts/jornal/')),
            ],
            bases=('cedoc.doc',),
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('doc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cedoc.Doc')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Video Duration')),
                ('language', models.CharField(blank=True, default='None', max_length=50, verbose_name='Language')),
                ('File', models.FileField(blank=True, upload_to='video/')),
            ],
            bases=('cedoc.doc',),
        ),
    ]
