# Generated by Django 2.0.5 on 2018-05-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='coverage',
            field=models.CharField(max_length=50, verbose_name='Coverage'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date',
            field=models.DateField(verbose_name='Document Date'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='fileFormat',
            field=models.CharField(choices=[('AN', 'Analog'), ('DG', 'Digital')], default='DG', max_length=2, verbose_name='Media Format'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='fileType',
            field=models.CharField(choices=[('.pdf', 'Portable Document Format (PDF)'), ('.txt', 'Documento de Texto'), ('.doc', 'Documento do Word'), ('.md', 'Markdown (MD)'), ('.jpg', 'Imagem JPG'), ('.png', 'Portable Network Graphics (PNG)'), ('.mp3', 'Arquivo de Áudio MP3')], default='.txt', max_length=5, verbose_name='File Format'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='language',
            field=models.CharField(max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='publisher',
            field=models.CharField(max_length=150, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='rights',
            field=models.CharField(max_length=100, verbose_name='Rights'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='submissionDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
