# Generated by Django 2.0.5 on 2018-06-14 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.CharField(default='Unknown', help_text='Name of Contributor', max_length=100, verbose_name='Contributor')),
                ('role', models.CharField(default='Contributor', help_text='Role of Contributor in the Project', max_length=100, verbose_name='Role')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedoc.Doc')),
            ],
        ),
        migrations.AddField(
            model_name='campusjournal',
            name='grafica',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gráfica'),
        ),
        migrations.AddField(
            model_name='campusjournal',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
    ]
