# Generated by Django 2.0.5 on 2018-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0002_auto_20180613_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='sender',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
