# Generated by Django 2.0.5 on 2018-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0002_auto_20180526_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='role',
            field=models.CharField(default='Contributor', max_length=100),
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='paper',
        ),
        migrations.AddField(
            model_name='contributor',
            name='paper',
            field=models.ManyToManyField(to='cedoc.Doc'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='coverage',
            field=models.CharField(choices=[('L', 'Local'), ('R', 'Regional'), ('I', 'International'), ('N', 'National')], max_length=2, verbose_name='Coverage'),
        ),
    ]
