# Generated by Django 2.0.6 on 2018-06-18 02:20

import cedoc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0003_doc_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusjournal',
            name='File',
            field=models.FileField(blank=True, upload_to='texts/jornal/', validators=[cedoc.validators.validate_CampusJournal]),
        ),
    ]
