# Generated by Django 2.0.5 on 2018-05-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0003_auto_20180526_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='language',
        ),
        migrations.AddField(
            model_name='textfile',
            name='language',
            field=models.CharField(default='Português', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='publisher',
            field=models.CharField(default='FAC-UnB', max_length=150, verbose_name='Publisher'),
        ),
    ]
