# Generated by Django 2.0.5 on 2018-05-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0004_auto_20180529_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='accepted',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Nao')], default=False, verbose_name='Accept file'),
        ),
    ]
