# Generated by Django 2.0.5 on 2018-06-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0004_auto_20180617_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusReporter',
            fields=[
                ('doc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cedoc.Doc')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Assunto')),
                ('collaborator', models.CharField(default='CEDOC', max_length=100, verbose_name='Collaborator')),
                ('address', models.CharField(default='CEDOC - FAC - UnB', max_length=150, verbose_name='Endereço')),
                ('printing', models.CharField(blank=True, max_length=50, verbose_name='Impressão')),
                ('tiragem', models.CharField(blank=True, max_length=50, verbose_name='Tiragem')),
                ('File', models.FileField(blank=True, upload_to='texts/reporter/')),
            ],
            bases=('cedoc.doc',),
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='campusjournal',
            name='language',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='language',
        ),
        migrations.AddField(
            model_name='doc',
            name='language',
            field=models.CharField(default='Português', max_length=50, verbose_name='Language'),
        ),
    ]
