# Generated by Django 2.0.5 on 2018-06-01 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0005_doc_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('doc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cedoc.Doc')),
                ('File', models.FileField(blank=True, upload_to='audio/')),
            ],
            bases=('cedoc.doc',),
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('doc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cedoc.Doc')),
                ('File', models.FileField(blank=True, upload_to='video/')),
            ],
            bases=('cedoc.doc',),
        ),
        migrations.AlterField(
            model_name='doc',
            name='fileType',
            field=models.CharField(default='.txt', max_length=5, verbose_name='File Format'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='File',
            field=models.FileField(blank=True, upload_to='texts/'),
        ),
    ]
