# Generated by Django 2.0.5 on 2018-06-01 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0006_auto_20180531_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Audio Duration'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='language',
            field=models.CharField(blank=True, default='None', max_length=50, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Video Duration'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='language',
            field=models.CharField(blank=True, default='None', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='fileType',
            field=models.CharField(choices=[('book', 'Printed Book'), ('blet', 'Printed Booklet'), ('atrc', 'Printed Article'), ('.pdf', 'Portable Document Format (PDF)'), ('.txt', 'Text Document'), ('.doc', 'Microsoft Word Document'), ('.docx', 'Office Open XML (DOCX)'), ('.odt', 'OpenDocument TExt File (ODT)'), ('.epub', 'Eletronic Publication (EPUB)'), ('.html', 'HyperText Markup Language (HTML)'), ('.md', 'Markdown (MD)'), ('.csv', 'Comma Separated Values (CSV)'), ('....', 'Photography Hard Copy'), ('.jpg', 'Imagem JPG'), ('.png', 'Portable Network Graphics (PNG)'), ('.gif', 'Graphics Interchange Format (GIF)'), ('.bmp', 'Windows bitmap (BMP)'), ('.cgm', 'Computer Graphics Metafile (CGM)'), ('.svg', 'Scalable Vector Graphics (SVG)'), ('.tif', 'Tagged Image File Format (TIFF)'), ('.cdr', 'CorelDRAW (CDR)'), ('.pdf', 'Portable Document Format (PDF)'), ('.mp3', 'MP3 Audio'), ('.wav', 'Microsoft Wave (WAV)'), ('.aif', 'Audio Interchange File Format (AIFF)'), ('.mp4', 'MP4 Format'), ('.mpeg', 'MPEG Format')], default='.txt', max_length=5, verbose_name='File Format'),
        ),
    ]
