# Generated by Django 2.0.5 on 2018-06-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0011_auto_20180620_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiovisual',
            old_name='video',
            new_name='categories',
        ),
    ]
