# Generated by Django 2.0.5 on 2018-06-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedoc', '0012_auto_20180620_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='rights',
            field=models.CharField(default='Creative Commons', help_text='Access Rights', max_length=100, verbose_name='Rights'),
        ),
    ]
